#!/bin/bash
source ~/python/EESARDocker/venv3/bin/activate
cd ~/python/EESARDocker/src
python setup.py install
python setup.py sdist
jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token=''
