# Dockerfile with Jupyter widget interface for 
# Sequential SAR on Earth Engine, Raspberry Pi

FROM     resin/rpi-raspbian:jessie
           
MAINTAINER Mort Canty "mort.canty@gmail.com"
ENV     REFRESHED_AT 2018-05-17

RUN apt-get update && apt-get install -y \
    python \
    build-essential \
    python-dev \
    libffi-dev \
    python-pygments \
    libzmq3-dev \
    pkg-config \
    python-pip 

EXPOSE 8888

# setup for earthengine
RUN     pip install pyasn1 --upgrade
RUN     pip install --upgrade setuptools && \
        pip install google-api-python-client && \
        pip install --upgrade oauth2client && \
        pip install pyCrypto && \
        apt-get install -y libssl-dev
RUN     pip install earthengine-api

# install auxil
COPY    dist/auxil-1.0.tar.gz /home/auxil-1.0.tar.gz
WORKDIR /home
RUN     tar -xzvf auxil-1.0.tar.gz
WORKDIR /home/auxil-1.0
RUN     python setup.py install  
WORKDIR /home
RUN     rm -rf auxil-1.0
RUN     rm auxil-1.0.tar.gz

# ipython notebook
RUN     pip install --upgrade pip
RUN     pip install jupyter==1.0.0
RUN     pip install ipyleaflet==0.9.0
RUN     jupyter nbextension enable --py --sys-prefix ipyleaflet

COPY    interface.ipynb /home/interface.ipynb
COPY    eesardocs.ipynb /home/eesardocs.ipynb

# ipython notebook startup script
ENV     REFRESHED_AT 2018-10-03
COPY    notebook.sh /
RUN     chmod u+x /notebook.sh

WORKDIR /home  
CMD     ["/notebook.sh"]
